apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
  template:
    metadata:
      labels:
        app: hello-gitops
    spec:
      containers:
      - name: hello
        image: nginx:1.25
        ports:
        - containerPort: 80
